@ECHO OFF
ECHO.
ECHO.
ECHO !!!!!     WARNNING     !!!!!
ECHO PLEASE, BE SURE TO THIS AS ADMINISTRATOR
ECHO OTHERWISE INQUISITOR CAN'T COLLECT SOME ARTIFACTS!
ECHO.
ECHO IF NOT IN ADMINISTRATOR MODE USE CTRL+C TO ABORT BATCH EXECUTION AND RESTART
ECHO.
ECHO.
PAUSE
FOR /F %%I IN ("%0") DO SET BATDIR=%%~dpI
powershell.exe -executionpolicy remotesigned -File %BATDIR%/inquisitor.ps1 -GUI
ECHO.
ECHO Hope you have enjoyed inquiring your system !!!
ECHO.
PAUSE


